-- help desk schema

-- Auto-update updatedAt on row changes.
create or replace function touchUpdatedAt()
returns trigger
language plpgsql
as $$
begin
  new.updatedAt = now();
  return new;
end;
$$;

create type userRole as enum ('admin', 'agent');
create type ticketStatus as enum ('new', 'open', 'pending', 'solved');
create type ticketPriority as enum ('low', 'normal', 'high', 'urgent');
create type messageKind as enum ('customer', 'reply', 'note');

-- An invited agent has an inviteToken and no passwordHash until they accept.
create table users (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  email text not null unique,
  name text not null default '',
  role userRole not null default 'agent',
  passwordHash text,
  inviteToken text unique,
  invitedAt timestamptz,
  acceptedAt timestamptz
);

create trigger usersTouchUpdatedAt
  before update on users
  for each row execute function touchUpdatedAt();

create table tickets (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  number int generated by default as identity (start with 1001) unique,
  subject text not null,
  customerName text not null,
  customerEmail text not null,
  status ticketStatus not null default 'new',
  priority ticketPriority not null default 'normal',
  assigneeId uuid references users (id) on delete set null,
  tags text[] not null default '{}',
  firstRepliedAt timestamptz,
  solvedAt timestamptz,
  lastMessageAt timestamptz not null default now()
);

create index ticketsStatusIdx on tickets (status);
create index ticketsAssigneeIdIdx on tickets (assigneeId);

create trigger ticketsTouchUpdatedAt
  before update on tickets
  for each row execute function touchUpdatedAt();

create table messages (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  ticketId uuid not null references tickets (id) on delete cascade,
  kind messageKind not null,
  authorId uuid references users (id) on delete set null,
  authorName text not null,
  body text not null
);

create index messagesTicketIdIdx on messages (ticketId, createdAt);

create trigger messagesTouchUpdatedAt
  before update on messages
  for each row execute function touchUpdatedAt();

create table cannedReplies (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  title text not null,
  body text not null
);

create trigger cannedRepliesTouchUpdatedAt
  before update on cannedReplies
  for each row execute function touchUpdatedAt();

-- One row per open ticket page, keyed by the page's listener.
create table ticketViewers (
  listenerId text primary key,
  createdAt timestamptz not null default now(),
  ticketId uuid not null,
  userId uuid not null,
  userName text not null,
  host text not null
);

create index ticketViewersTicketIdIdx on ticketViewers (ticketId);
create index ticketViewersHostIdx on ticketViewers (host);

-- Replies, the contact form and ticket edits write with plain sql, so the
-- tables announce their own writes. The payload is the id; each app server
-- reads the row back through the LiveTable's select.
create or replace function notifyById() returns trigger
language plpgsql as $$
declare
  r record;
begin
  r := coalesce(new, old);

  perform pg_notify(
    channel_name(tg_argv[0]),
    json_build_object('op', lower(tg_op), 'id', r.id)::text
  );

  return r;
end;
$$;

create trigger ticketsNotifyTrigger
  after insert or update or delete on tickets
  for each row execute function notifyById('tickets');

create trigger messagesNotifyTrigger
  after insert or update or delete on messages
  for each row execute function notifyById('messages');
